backend:
  name: github
  repo: gregleeper/hrc #replace with your username/repo

media_folder: static/assets

collections:
  - name: schedules
    label: Schedules
    folder: schedules
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
